package com.diploma.mrt.codegen;

import com.diploma.mrt.entity.ArtifactType;
import com.diploma.mrt.entity.AuditAction;
import com.diploma.mrt.entity.CaseOrigin;
import com.diploma.mrt.entity.CaseResultSource;
import com.diploma.mrt.entity.CaseStatus;
import com.diploma.mrt.entity.DemoCategory;
import com.diploma.mrt.entity.ExecutionMode;
import com.diploma.mrt.entity.FindingType;
import com.diploma.mrt.entity.InferenceStatus;
import com.diploma.mrt.entity.Modality;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Generates the TypeScript contract bundle from the JVM-side wire model.
 * The wire form for each enum is obtained by serializing it through Jackson
 * (so {@code @JsonValue} overrides are honored), making this generator the
 * single source of truth for what the API actually emits.
 */
public final class FrontendContractGenerator {
    private FrontendContractGenerator() {}

    private static final List<EnumSpec<?>> ENUMS = List.of(
            new EnumSpec<>(ArtifactType.class, "ARTIFACT_TYPES", "ArtifactType"),
            new EnumSpec<>(AuditAction.class, "AUDIT_ACTIONS", "AuditAction"),
            new EnumSpec<>(CaseOrigin.class, "CASE_ORIGINS", "CaseOrigin"),
            new EnumSpec<>(CaseResultSource.class, "CASE_RESULT_SOURCES", "CaseResultSource"),
            new EnumSpec<>(CaseStatus.class, "CASE_STATUSES", "CaseStatus"),
            new EnumSpec<>(DemoCategory.class, "DEMO_CATEGORIES", "DemoCategory"),
            new EnumSpec<>(ExecutionMode.class, "EXECUTION_MODES", "ExecutionMode"),
            new EnumSpec<>(FindingType.class, "FINDING_TYPES", "FindingType"),
            new EnumSpec<>(InferenceStatus.class, "INFERENCE_STATUSES", "InferenceStatus"),
            new EnumSpec<>(Modality.class, "MODALITIES", "Modality")
    );

    public static void main(String[] args) throws Exception {
        boolean check = false;
        Path outputPath = null;
        for (int i = 0; i < args.length; i++) {
            switch (args[i]) {
                case "--check" -> check = true;
                case "--output" -> outputPath = Path.of(args[++i]);
                default -> throw new IllegalArgumentException("Unknown argument: " + args[i]);
            }
        }
        if (outputPath == null) {
            throw new IllegalArgumentException("--output <path> is required");
        }

        String expected = render();
        if (check) {
            String actual = Files.exists(outputPath) ? Files.readString(outputPath) : "";
            if (!actual.equals(expected)) {
                System.err.println("Frontend contract is out of date: " + outputPath);
                System.exit(1);
            }
            return;
        }

        Files.createDirectories(outputPath.getParent());
        Files.writeString(outputPath, expected);
    }

    static String render() {
        ObjectMapper mapper = new ObjectMapper();
        StringBuilder out = new StringBuilder();
        out.append("// Generated by com.diploma.mrt.codegen.FrontendContractGenerator from the backend wire model.\n");
        out.append("// Do not edit manually.\n\n");
        boolean first = true;
        for (EnumSpec<?> spec : ENUMS) {
            if (!first) {
                out.append('\n');
            }
            first = false;
            out.append(renderEnum(spec, mapper));
        }
        return out.toString();
    }

    private static <E extends Enum<E>> String renderEnum(EnumSpec<E> spec, ObjectMapper mapper) {
        Map<String, String> entries = new LinkedHashMap<>();
        for (E constant : spec.type.getEnumConstants()) {
            String wireValue;
            try {
                wireValue = stripQuotes(mapper.writeValueAsString(constant));
            } catch (Exception exception) {
                throw new IllegalStateException("Failed to serialize " + spec.type.getName() + "." + constant.name(), exception);
            }
            entries.put(constant.name(), wireValue);
        }
        StringBuilder block = new StringBuilder();
        block.append("export const ").append(spec.constName).append(" = {\n");
        for (Map.Entry<String, String> entry : entries.entrySet()) {
            block.append("  ").append(entry.getKey()).append(": '").append(escape(entry.getValue())).append("',\n");
        }
        block.append("} as const\n\n");
        block.append("export type ").append(spec.typeName)
                .append(" = (typeof ").append(spec.constName).append(")[keyof typeof ").append(spec.constName).append("]\n");
        return block.toString();
    }

    private static String stripQuotes(String json) {
        if (json.length() >= 2 && json.startsWith("\"") && json.endsWith("\"")) {
            return json.substring(1, json.length() - 1);
        }
        return json.toLowerCase(Locale.ROOT);
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("'", "\\'");
    }

    private record EnumSpec<E extends Enum<E>>(Class<E> type, String constName, String typeName) {
        @SuppressWarnings("unused")
        E[] values() {
            return type.getEnumConstants();
        }
        @SuppressWarnings("unused")
        List<E> valuesList() {
            return Arrays.asList(type.getEnumConstants());
        }
    }
}
