// Generated by com.diploma.mrt.codegen.FrontendContractGenerator from the backend wire model.
// Do not edit manually.

export const ARTIFACT_TYPES = {
  ORIGINAL_STUDY: 'ORIGINAL_STUDY',
  ENHANCED_VOLUME: 'ENHANCED_VOLUME',
  LIVER_MASK: 'LIVER_MASK',
  LESION_MASK: 'LESION_MASK',
  LIVER_MESH: 'LIVER_MESH',
  LESION_MESH: 'LESION_MESH',
} as const

export type ArtifactType = (typeof ARTIFACT_TYPES)[keyof typeof ARTIFACT_TYPES]

export const AUDIT_ACTIONS = {
  CASE_CREATED: 'CASE_CREATED',
  CASE_UPLOADED: 'CASE_UPLOADED',
  DEMO_CASE_IMPORTED: 'DEMO_CASE_IMPORTED',
  DEMO_CASE_UPDATED: 'DEMO_CASE_UPDATED',
  INFERENCE_ENQUEUED: 'INFERENCE_ENQUEUED',
  INFERENCE_STARTED: 'INFERENCE_STARTED',
  INFERENCE_REQUEST_SENT: 'INFERENCE_REQUEST_SENT',
  INFERENCE_COMPLETED: 'INFERENCE_COMPLETED',
  INFERENCE_FAILED: 'INFERENCE_FAILED',
  INFERENCE_RECOVERED_AFTER_RESTART: 'INFERENCE_RECOVERED_AFTER_RESTART',
} as const

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS]

export const CASE_ORIGINS = {
  LIVE_PROCESSED: 'LIVE_PROCESSED',
  SEEDED_DEMO: 'SEEDED_DEMO',
} as const

export type CaseOrigin = (typeof CASE_ORIGINS)[keyof typeof CASE_ORIGINS]

export const CASE_RESULT_SOURCES = {
  NONE: 'NONE',
  ML_INFERENCE: 'ML_INFERENCE',
  SEEDED_IMPORT: 'SEEDED_IMPORT',
} as const

export type CaseResultSource = (typeof CASE_RESULT_SOURCES)[keyof typeof CASE_RESULT_SOURCES]

export const CASE_STATUSES = {
  CREATED: 'CREATED',
  UPLOADED: 'UPLOADED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const

export type CaseStatus = (typeof CASE_STATUSES)[keyof typeof CASE_STATUSES]

export const DEMO_CATEGORIES = {
  NORMAL: 'NORMAL',
  SINGLE_LESION: 'SINGLE_LESION',
  MULTIFOCAL: 'MULTIFOCAL',
  DIFFICULT: 'DIFFICULT',
} as const

export type DemoCategory = (typeof DEMO_CATEGORIES)[keyof typeof DEMO_CATEGORIES]

export const EXECUTION_MODES = {
  MOCK: 'mock',
  REAL: 'real',
} as const

export type ExecutionMode = (typeof EXECUTION_MODES)[keyof typeof EXECUTION_MODES]

export const FINDING_TYPES = {
  LESION: 'LESION',
} as const

export type FindingType = (typeof FINDING_TYPES)[keyof typeof FINDING_TYPES]

export const INFERENCE_STATUSES = {
  STARTED: 'STARTED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const

export type InferenceStatus = (typeof INFERENCE_STATUSES)[keyof typeof INFERENCE_STATUSES]

export const MODALITIES = {
  MRI: 'MRI',
  CT: 'CT',
} as const

export type Modality = (typeof MODALITIES)[keyof typeof MODALITIES]
