package com.diploma.mrt.entity;

public enum AuditAction {
    CASE_CREATED,
    CASE_UPLOADED,
    DEMO_CASE_IMPORTED,
    DEMO_CASE_UPDATED,
    INFERENCE_ENQUEUED,
    INFERENCE_STARTED,
    INFERENCE_REQUEST_SENT,
    INFERENCE_COMPLETED,
    INFERENCE_FAILED,
    INFERENCE_RECOVERED_AFTER_RESTART
}
